import { modalState } from '@/atoms/globalAtom';
import { ModalVideoPlayer } from '@/components/UI';
import { Movie } from '@/types/global';
import { requests_tv_shows } from '@/utils/requests';
import { useEffect, useState } from 'react';
import { useRecoilValue } from 'recoil';

import Banner from '@/components/Banner';
import Layout from '@/components/Layout';
import MovieRow from '@/components/MovieRow';

interface Props {
  airingToday: Movie[];
  onTheAir: Movie[];
  popular: Movie[];
  topRated: Movie[];
}

const TvShow = ({ airingToday, onTheAir, popular, topRated }: Props) => {
  const [randomMovie, setRandomMovie] = useState<Movie | null>(null);
  const showModal = useRecoilValue(modalState);

  useEffect(() => {
    setRandomMovie(topRated[Math.floor(Math.random() * topRated.length)]);
  }, [topRated]);

  return (
    <Layout
      title="TV Show - Netflix"
      description="Generated by create next app"
    >
      <Banner movie={randomMovie} />
      <section className="flex flex-col md:space-y-24">
        <MovieRow title="On TV" movies={onTheAir} />
        <MovieRow title="Airing Today" movies={airingToday} />
        <MovieRow title="Popular" movies={popular} />
        <MovieRow title="Top Rated" movies={topRated} />
      </section>
      {showModal && <ModalVideoPlayer />}
    </Layout>
  );
};

export const getServerSideProps = async () => {
  const [airingToday, onTheAir, popular, topRated] = await Promise.all([
    fetch(requests_tv_shows.fetchAiringToday).then((res) => res.json()),
    fetch(requests_tv_shows.fetchOnTheAir).then((res) => res.json()),
    fetch(requests_tv_shows.fetchPopular).then((res) => res.json()),
    fetch(requests_tv_shows.fetchTopRated).then((res) => res.json()),
  ]);

  return {
    props: {
      airingToday: airingToday.results,
      onTheAir: onTheAir.results,
      popular: popular.results,
      topRated: topRated.results,
    },
  };
};

export default TvShow;
