import { bookmarkMovieState, likedMovieState } from '@/atoms/modalAtom';
import { modalState } from '@/atoms/modalAtom';
import Banner from '@/components/Banner';
import Layout from '@/components/Layout';
import MovieRow from '@/components/MovieRow';
import { ModalVideoPlayer } from '@/components/UI';
import { Movie } from '@/types/global';
import { requests } from '@/utils/requests';
import React, { useEffect, useState } from 'react';
import { useRecoilValue } from 'recoil';

interface Props {
  trendingNow: Movie[];
}

const MyList = ({ trendingNow }: Props) => {
  const myListMovie = useRecoilValue(bookmarkMovieState);
  const likedMovie = useRecoilValue(likedMovieState);
  const [randomMovie, setRandomMovie] = useState<Movie | null>(null);
  const showModal = useRecoilValue(modalState);

  useEffect(() => {
    setRandomMovie(trendingNow[Math.floor(Math.random() * trendingNow.length)]);
  }, [trendingNow]);

  return (
    <Layout title="Home - Netflix" description="Generated by create next app">
      <Banner movie={randomMovie} />
      <MovieRow title="My List" movies={myListMovie} />
      <MovieRow title="Favorite Movie" movies={likedMovie} />
      {showModal && <ModalVideoPlayer />}
    </Layout>
  );
};

export default MyList;

export const getServerSideProps = async () => {
  const trendingNow = await fetch(requests.fetchTrending).then((res) =>
    res.json()
  );

  return {
    props: {
      trendingNow: trendingNow.results,
    },
  };
};
